# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/gradle/standard_jetbrains_plugin/"
    schedule:
      interval: "daily"
    labels:
      - "merge when passing"  # This is a label that [Repo Ranger](https://github.com/apps/repo-ranger) will pickup and auto-merge when all GH checks pass.
    reviewers:
      - ChrisCarini

  # Maintain dependencies for GitHub Actions (for **other** repos' workflow files)
  - package-ecosystem: "github-actions"
    directory: "/github/workflows/"
    schedule:
      interval: "daily"
    labels:
      - "merge when passing"  # This is a label that [Repo Ranger](https://github.com/apps/repo-ranger) will pickup and auto-merge when all GH checks pass.
    reviewers:
      - ChrisCarini

  # Maintain dependencies for GitHub Actions (for **this** repo's workflow files)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "merge when passing"  # This is a label that [Repo Ranger](https://github.com/apps/repo-ranger) will pickup and auto-merge when all GH checks pass.
    reviewers:
      - ChrisCarini
