name: Repo Sync
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  ##############################
  #       SYNC REPO FILES      #
  ##############################
  sync_repo_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

      - name: Run Repo File Sync Action
        id: repo-file-sync
#        Use my own fork for now, as I want to try out a few new features I'm adding...
#        uses: BetaHuhn/repo-file-sync-action@v1
        uses: ChrisCarini/repo-file-sync-action@main
        with:
          ASSIGNEES: |
            ChrisCarini
          # NOTE: As much as I would like to be marked to review each of these, because
          # this GitHub Action uses a PAT, the commit is coming from myself (ie, `ChrisCarini`)
          # and thus, trying to set myself as a reviewer yields the below error message:
          #
          #   "Error: Review cannot be requested from pull request author."
          #
          # REVIEWERS: |
          #   ChrisCarini
          PR_LABELS: |
            repo-file-sync
          ORIGINAL_MESSAGE: true
          CONFIG_PATH: sync.yml
          GH_PAT: ${{ secrets.GH_PAT_REPO_WORKFLOW_SCOPE }}

      - name: List PRs
        run: |
          echo "${STEPS__REPO_FILE_SYNC__OUTPUTS__PULL_REQUEST_URLS}" | jq .
        env:
          STEPS__REPO_FILE_SYNC__OUTPUTS__PULL_REQUEST_URLS: "${{ steps.repo-file-sync.outputs.pull_request_urls }}"

  ##############################
  #     SYNC REPO SETTINGS     #
  ##############################
  sync_repo_settings:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Repo Settings - public
        uses: kbrashears5/github-action-repo-settings-sync@2.0
        with:
          REPOSITORIES: |
            ChrisCarini/automatic-github-issue-navigation-configuration-jetbrains-plugin
            ChrisCarini/environment-variable-settings-summary-intellij-plugin
            ChrisCarini/example-loc-plugin-config-plugin
            ChrisCarini/git-push-reminder-jetbrains-plugin
            ChrisCarini/github-repo-files-sync
            ChrisCarini/ieee-csdl-downloader
            ChrisCarini/intellij-code-exfiltration
            ChrisCarini/intellij-notification-sample
            ChrisCarini/iris-jetbrains-plugin
            ChrisCarini/jetbrains-auto-power-saver
            ChrisCarini/jetbrains-ide-release-dates
            ChrisCarini/loc-change-count-detector-jetbrains-plugin
            ChrisCarini/logshipper-intellij-plugin
            ChrisCarini/sample-intellij-plugin
            ChrisCarini/shodan-exposure-box
            ChrisCarini/trivia-box
            ChrisCarini/upptime
          ALLOW_WIKI: 'true'
          ALLOW_ISSUES: 'true'
          ALLOW_PROJECTS: 'true'

          MERGE_COMMIT: 'false'
          SQUASH_MERGE: 'true'
          REBASE_MERGE: 'false'

          AUTO_MERGE: 'true'

          DELETE_HEAD: 'true'

          # NOTE: The below is marked `UNCHANGED` and the remainder are commented because otherwise
          # running this action will end up 'un-setting' the 'required status checks'. :(
          BRANCH_PROTECTION_ENABLED: 'UNCHANGED'
          #          BRANCH_PROTECTION_NAME: 'main'
          #          BRANCH_PROTECTION_REQUIRED_REVIEWERS: '0'
          #          BRANCH_PROTECTION_DISMISS: 'true'
          #          BRANCH_PROTECTION_CODE_OWNERS: 'false'
          #          BRANCH_PROTECTION_ENFORCE_ADMINS: 'false'
          TOKEN: ${{ secrets.GH_PAT_REPO_SCOPE }}

      - name: Sync Repo Settings - private
        uses: kbrashears5/github-action-repo-settings-sync@2.0
        with:
          REPOSITORIES: |
            ChrisCarini/fitbit-data-extract
            ChrisCarini/jetbrains-sdk-cleaner
          ALLOW_WIKI: 'false' # This option is only available for public repos :(
          ALLOW_ISSUES: 'true'
          ALLOW_PROJECTS: 'true'

          MERGE_COMMIT: 'false'
          SQUASH_MERGE: 'true'
          REBASE_MERGE: 'false'

          AUTO_MERGE: 'false' # This option is only available for public repos :(

          DELETE_HEAD: 'true'

          # NOTE: The below is marked `UNCHANGED` and the remainder are commented because otherwise
          # running this action will end up 'un-setting' the 'required status checks'. :(
          BRANCH_PROTECTION_ENABLED: 'UNCHANGED'
          #          BRANCH_PROTECTION_NAME: 'main'
          #          BRANCH_PROTECTION_REQUIRED_REVIEWERS: '0'
          #          BRANCH_PROTECTION_DISMISS: 'true'
          #          BRANCH_PROTECTION_CODE_OWNERS: 'false'
          #          BRANCH_PROTECTION_ENFORCE_ADMINS: 'false'
          TOKEN: ${{ secrets.GH_PAT_REPO_SCOPE }}
